# Generated by Django 4.1.4 on 2023-08-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookList',
        ),
    ]
