# Generated by Django 4.1.4 on 2023-08-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productline',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='productImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alternative_text', models.CharField(max_length=200)),
                ('url', models.ImageField(upload_to='products/')),
                ('productLine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productline')),
            ],
        ),
    ]
